### ISSUE TITLE
TemplateNotFound error when trying to access CFG from browser

### ISSUE THREAD

**Issue by ghost** [axt/cfg-explorer#1]
Hello,

I'm running into a Jinja/Flask template error when trying to access the CFG from localhost:5000. Here is the error listed in the traceback: 

**jinja2.exceptions.TemplateNotFound**

Any advice would be greatly appreciated!

**Comment by axt** [comment]
Hi! I'm sorry for my late answer!

Templates are only used when rendering the `index.html`. Can you tell me, how you are running the project? I've just tested it with running it from the checked-out git directory by issueing `./start.py`, or doing a `pip -e` (editable) install, and issueing `python -m cfgexplorer`.

If you are on linux, you can debug where it tries to look for the `index.html` with using `strace`:
```
strace python ./start.py a.out |& grep 'index.html'
```

(Please note, that this project is just meant to be a simple toy example, to demonstrate the features of my other incubating state project https://github.com/axt/bingraphvis, which is a CFG visualizer pipeline for https://github.com/angr/angr/ generated CFGs. I'm not sure it is usable at all with real life apps, I've just used it with some smaller samples. It has a lot of limitations, for example the "interactivity" is really simple (just some clickable SVGs), which suit my needs in my experimentations, but probably are a heavy limit in using it as a tool for real-life apps.)
