### ISSUE TITLE
How to get a graph class before serialization

### ISSUE THREAD

**Issue by zetta-cai** [axt/cfg-explorer#6]
hello,
I was wondering if I want to extract the control flow graph and put it into a graph data structure. How should I do it?

**Comment by axt** [comment]
This repo uses https://github.com/angr/angr for creating the CFG.

Here is a simple example:
```
import angr
project = angr.Project('binary', load_options={'auto_load_libs': False})
cfg = project.analyses.CFGFast()
```

The cfg object here will be the CFG graph itself. It has a '.nodes()' and '.edges()' function, check angr tutorials for more info.
